version: '3'
services:
  back-end:
    image: lambdafr/td3mlops:latest
    
    ports:
      - "8080:8080"
    volumes:   # volumes va indiquer le chemin jusque là où les données seront stockées
      - .\app\data   # j'ai créé ce dossier data pour indiquer où les données seront stockées
    environment:
      - CURRENT_ENVIRONMENT=production

  front-end:
    image: lambdafr/td3mlops:front
    ports:
      - "80:80"
    environment:
      - WS_BACK_URL=localhost:8080
