version: '3'
services:
  back-end:
    image: lambdafr/td3mlops:latest
    ports:
      - "8080:8080"
    environment:
      - CURRENT_ENVIRONMENT=production

  front-end:
    image: lambdafr/td3mlops:front
    ports:
      - "80:80"
    environment:
      - WS_BACK_URL=localhost:8080
